### ISSUE TITLE
[Epic]: Use helm chart for local and production deployment

### ISSUE THREAD

**Issue by jezekra1** [i-am-bee/bee-stack#27]
The goal is to replace docker-compose by a helm chart that can be deployed both on local machine in the following kubernetes runtimes: Docker Desktop, Rancher Desktop, Podman.

Initial local helm chart: https://github.com/i-am-bee/bee-stack/pull/14
Subtasks:
- [ ] [Create initial helm chart with all components working locally](https://github.com/i-am-bee/bee-stack/issues/28)
- [ ] [Add support for external infrastructure (mongo, redis, milvus, minio)](https://github.com/i-am-bee/bee-stack/issues/19)
- [ ] [Handle seeders and migrations - make them optional init containers / helm hooks](https://github.com/i-am-bee/bee-stack/issues/20)
- [ ] [Secret management - add support for production secrets as well as dummy auth currently used locally](https://github.com/i-am-bee/bee-stack/issues/21)
- [ ] [Add support for production UI image (pre-built with different NEXT build arguments)](https://github.com/i-am-bee/bee-stack/issues/22)
- [ ] [Scaling configuration and support for worker pods](https://github.com/i-am-bee/bee-stack/issues/23)
- [ ] [Ingress configuration & local port-forwarding](https://github.com/i-am-bee/bee-stack/issues/24)
- [ ] [Add optional opentelemetry collector](https://github.com/i-am-bee/bee-stack/issues/25)
- [ ] [Add required proxy for api call tool in production](https://github.com/i-am-bee/bee-stack/issues/26)

**Comment by planetf1** [comment]
If this is targetting production, and even for development (where developer may have access to a shared cluster), would it also be possible to consider Red Hat openshift.

**Comment by aditya-nv-06** [comment]
Can i also work in this issue.

**Comment by matoushavlena** [comment]
Closing this issue as the repository has been archived and is no longer actively maintained. Thank you for your contribution and understanding!
